name: Update Citations
on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday at 00:00
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install scholarly pyyaml
          
      - name: Run citation updater
        run: |
          python scripts/update_citations.py
          
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add _data/citations.yml
          git commit -m "Update citation counts" || echo "No changes to commit"
          git push
